# Generated by Django 4.0 on 2022-02-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Toko',
        ),
    ]
