# Generated by Django 4.0 on 2022-02-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0002_rename_post_toko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toko',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='toko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surv.toko'),
        ),
    ]
