# Generated by Django 4.0 on 2022-02-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0003_remove_toko_answer_answer_toko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
