# Generated by Django 4.0 on 2022-02-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0004_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
