# Generated by Django 4.0 on 2022-02-16 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0006_toko_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toko',
            old_name='sum',
            new_name='nsum',
        ),
    ]
