# Generated by Django 4.0 on 2022-02-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0007_rename_sum_toko_nsum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=10)),
            ],
        ),
    ]
