# Generated by Django 4.0 on 2022-02-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='toko',
            field=models.ManyToManyField(to='surv.Toko'),
        ),
    ]
